// Generated by Shadesmith from Minecraft 26.2
// version_metadata_sha1: d98675ecc24364e90b18dbea80390b1345c3f71f
// client_sha1: 2dc72797acbc1b63fc16a11c4ac393605f453754
#ifndef INCLUDE_techniques_voxel_BlockModels_glsl
#define INCLUDE_techniques_voxel_BlockModels_glsl a

float _voxel_rotateBlockModelComponent(uint transform, vec3 value) {
    float result = value[int(transform & 3u)];
    return (transform & 4u) == 0u ? result : -result;
}

vec3 _voxel_rotateBlockModelVector(uint rotation, vec3 value) {
    return vec3(
        _voxel_rotateBlockModelComponent(rotation, value),
        _voxel_rotateBlockModelComponent(rotation >> 3u, value),
        _voxel_rotateBlockModelComponent(rotation >> 6u, value)
    );
}

vec3 _voxel_unrotateBlockModelVector(uint rotation, vec3 value) {
    vec3 result = vec3(0.0);
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.x : -value.x;
    rotation >>= 3u;
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.y : -value.y;
    rotation >>= 3u;
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.z : -value.z;
    return result;
}

bool _voxel_intersectBlockModelQuad(
    vec3 rayOrigin, vec3 rayDir, uint quadIndex, inout float hitT, inout vec3 hitNormal
) {
    int texelIndex = int(quadIndex * 2u);
    vec4 originNormalX = texelFetch(usam_blockModelQuads, texelIndex, 0);
    vec4 normalYZHalfSize = texelFetch(usam_blockModelQuads, texelIndex + 1, 0);
    vec3 origin = originNormalX.xyz;
    vec3 normal = normalize(vec3(originNormalX.w, normalYZHalfSize.xy) * (255.0 / 126.0) - 1.0);
    vec2 halfSize = normalYZHalfSize.zw + 1e-6;
    float denominator = dot(normal, rayDir);
    if (abs(denominator) <= 1e-8) return false;
    float t = dot(normal, origin - rayOrigin) / denominator;
    if (!(t >= 0.0 && t <= hitT)) return false;
    vec3 axis = abs(normal.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(0.0, 1.0, 0.0);
    vec3 u = normalize(cross(axis, normal));
    vec3 v = cross(normal, u);
    vec3 offset = rayOrigin + rayDir * t - origin;
    vec2 projected = abs(vec2(dot(offset, u), dot(offset, v)));
    if (any(greaterThan(projected, halfSize))) return false;
    hitT = t;
    hitNormal = denominator < 0.0 ? normal : -normal;
    return true;
}

bool voxel_intersectBlockModel(
    uint modelData, vec3 rayOrigin, vec3 rayDir,
    out float hitT, out vec3 hitNormal
) {
    uint rotation = modelData & 0x1FFu;
    uint quadOffset = (modelData >> 9u) & 0xFFFFu;
    uint quadCount = modelData >> 25u;
    rayOrigin = _voxel_rotateBlockModelVector(rotation, rayOrigin - vec3(0.5)) + vec3(0.5);
    rayDir = _voxel_rotateBlockModelVector(rotation, rayDir);
    hitT = uintBitsToFloat(0x7F800000u);
    hitNormal = vec3(0.0);
    bool hit = false;
    for (uint i = 0u; i < quadCount; ++i) {
        hit = _voxel_intersectBlockModelQuad(rayOrigin, rayDir, quadOffset + i, hitT, hitNormal) || hit;
    }
    if (hit) hitNormal = _voxel_unrotateBlockModelVector(rotation, hitNormal);
    return hit;
}

#endif
