// Generated by Shadesmith from Minecraft 26.2
// version_metadata_sha1: 4b74f58f68a2baae3547d5a20274079f29cafc06
// client_sha1: 2dc72797acbc1b63fc16a11c4ac393605f453754
#ifndef INCLUDE_techniques_voxel_BlockModels_glsl
#define INCLUDE_techniques_voxel_BlockModels_glsl a

void _voxel_rotateBlockModelRay(uint rotation, inout vec3 rayOrigin, inout vec3 rayDir) {
    uvec3 transform = uvec3(rotation, rotation >> 3u, rotation >> 6u);
    ivec3 axis = ivec3(transform & 3u);
    vec3 transformSign = mix(vec3(1.0), vec3(-1.0), notEqual(transform & 4u, uvec3(0u)));
    rayOrigin = vec3(rayOrigin[axis.x], rayOrigin[axis.y], rayOrigin[axis.z]) * transformSign;
    rayDir = vec3(rayDir[axis.x], rayDir[axis.y], rayDir[axis.z]) * transformSign;
}

vec3 _voxel_unrotateBlockModelVector(uint rotation, vec3 value) {
    vec3 result = vec3(0.0);
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.x : -value.x;
    rotation >>= 3u;
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.y : -value.y;
    rotation >>= 3u;
    result[int(rotation & 3u)] = (rotation & 4u) == 0u ? value.z : -value.z;
    return result;
}

vec3 _voxel_rotateBlockModelQuaternion(vec4 quaternion, vec3 value) {
    return value + 2.0 * cross(quaternion.xyz, cross(quaternion.xyz, value) + quaternion.w * value);
}

uint _voxel_expandBlockModelRotation(uint rotation) {
    uint x = rotation & 7u;
    uint y = (rotation >> 3u) & 7u;
    uint xAxis = x & 3u;
    uint yAxis = y & 3u;
    uint zAxis = 3u - xAxis - yAxis;
    uint z = zAxis | ((rotation >> 4u) & 4u);
    return x | (y << 3u) | (z << 6u);
}

bool _voxel_intersectBlockModelAABB(
    vec3 rayOrigin, vec3 rayDir, int texelIndex, float rayMinT, float rayMaxT,
    inout float hitT, inout vec3 hitNormal
) {
    vec4 originData = texelFetch(usam_blockModelAABBs, texelIndex + 1, 0);
    uint discreteRotation = uint(originData.w * 255.0 + 0.5);
    bool discrete = discreteRotation != 255u;
    if (discrete) discreteRotation = _voxel_expandBlockModelRotation(discreteRotation);
    vec4 quaternion = vec4(0.0, 0.0, 0.0, 1.0);
    vec3 origin = originData.xyz;
    vec3 halfSize = texelFetch(usam_blockModelAABBs, texelIndex + 2, 0).xyz * 1.4142135623730951 * 0.5 + 1e-6;
    vec3 localOrigin = rayOrigin - origin;
    vec3 localDir = rayDir;
    if (discrete) {
        _voxel_rotateBlockModelRay(discreteRotation, localOrigin, localDir);
    } else {
        quaternion = normalize(texelFetch(usam_blockModelAABBs, texelIndex, 0) * (255.0 / 126.0) - 1.0);
        vec4 inverseQuaternion = vec4(-quaternion.xyz, quaternion.w);
        localOrigin = _voxel_rotateBlockModelQuaternion(inverseQuaternion, localOrigin);
        localDir = _voxel_rotateBlockModelQuaternion(inverseQuaternion, localDir);
    }
    float entryT = -uintBitsToFloat(0x7F800000u);
    float exitT = uintBitsToFloat(0x7F800000u);
    int entryAxis = 0;
    int exitAxis = 0;
#ifdef VOXEL_BLOCK_MODEL_UNROLL_SLABS
    {
        if (abs(localDir.x) <= 1e-6) {
            if (abs(localOrigin.x) > halfSize.x) return false;
        } else {
            float signedHalfSize = halfSize.x * sign(localDir.x);
            float nearT = (-signedHalfSize - localOrigin.x) / localDir.x;
            float farT = (signedHalfSize - localOrigin.x) / localDir.x;
            if (nearT > entryT) {
                entryT = nearT;
                entryAxis = 0;
            }
            if (farT < exitT) {
                exitT = farT;
                exitAxis = 0;
            }
            if (entryT > exitT) return false;
        }
    }
    {
        if (abs(localDir.y) <= 1e-6) {
            if (abs(localOrigin.y) > halfSize.y) return false;
        } else {
            float signedHalfSize = halfSize.y * sign(localDir.y);
            float nearT = (-signedHalfSize - localOrigin.y) / localDir.y;
            float farT = (signedHalfSize - localOrigin.y) / localDir.y;
            if (nearT > entryT) {
                entryT = nearT;
                entryAxis = 1;
            }
            if (farT < exitT) {
                exitT = farT;
                exitAxis = 1;
            }
            if (entryT > exitT) return false;
        }
    }
    {
        if (abs(localDir.z) <= 1e-6) {
            if (abs(localOrigin.z) > halfSize.z) return false;
        } else {
            float signedHalfSize = halfSize.z * sign(localDir.z);
            float nearT = (-signedHalfSize - localOrigin.z) / localDir.z;
            float farT = (signedHalfSize - localOrigin.z) / localDir.z;
            if (nearT > entryT) {
                entryT = nearT;
                entryAxis = 2;
            }
            if (farT < exitT) {
                exitT = farT;
                exitAxis = 2;
            }
            if (entryT > exitT) return false;
        }
    }
#else
    for (int axis = 0; axis < 3; ++axis) {
        if (abs(localDir[axis]) <= 1e-6) {
            if (abs(localOrigin[axis]) > halfSize[axis]) return false;
            continue;
        }
        float signedHalfSize = halfSize[axis] * sign(localDir[axis]);
        float nearT = (-signedHalfSize - localOrigin[axis]) / localDir[axis];
        float farT = (signedHalfSize - localOrigin[axis]) / localDir[axis];
        if (nearT > entryT) {
            entryT = nearT;
            entryAxis = axis;
        }
        if (farT < exitT) {
            exitT = farT;
            exitAxis = axis;
        }
    }
    if (entryT > exitT) return false;
#endif
    float maxT = min(rayMaxT, hitT);
    bool exitsInside = entryT < rayMinT && exitT <= maxT;
    float t = entryT < rayMinT ? (exitsInside ? exitT : rayMinT) : entryT;
    if (exitT < rayMinT || t > maxT) return false;
    int normalAxis = exitsInside ? exitAxis : entryAxis;
    vec3 localNormal = vec3(0.0);
    localNormal[normalAxis] = -sign(localDir[normalAxis]);
    hitT = t;
    if (discrete) {
        hitNormal = _voxel_unrotateBlockModelVector(discreteRotation, localNormal);
    } else {
        hitNormal = _voxel_rotateBlockModelQuaternion(quaternion, localNormal);
    }
    return true;
}

bool voxel_intersectBlockModel(
    uint modelData, vec3 rayOrigin, vec3 rayDir, float rayMinT, float rayMaxT,
    out float hitT, out vec3 hitNormal
) {
    uint rotation = modelData & 511u;
    uint aabbOffset = (modelData >> 9u) & 0x7FFFu;
    uint aabbCount = modelData >> 24u;
    rayOrigin -= vec3(0.5);
    _voxel_rotateBlockModelRay(rotation, rayOrigin, rayDir);
    rayOrigin += vec3(0.5);
    const float noHitT = uintBitsToFloat(0x7F800000u);
    hitT = noHitT;
    hitNormal = vec3(0.0);
#ifdef VOXEL_BLOCK_MODEL_LINEAR_AABB_TEXELS
    int texelIndex = int(aabbOffset * 3u);
    for (uint i = 0u; i < aabbCount; ++i) {
        _voxel_intersectBlockModelAABB(
            rayOrigin, rayDir, texelIndex, rayMinT, rayMaxT, hitT, hitNormal
        );
        texelIndex += 3;
    }
#else
    if (aabbCount == 1u) {
        _voxel_intersectBlockModelAABB(
            rayOrigin, rayDir, int(aabbOffset * 3u), rayMinT, rayMaxT, hitT, hitNormal
        );
    } else {
        for (uint i = 0u; i < aabbCount; ++i) {
            _voxel_intersectBlockModelAABB(
                rayOrigin, rayDir, int((aabbOffset + i) * 3u), rayMinT, rayMaxT, hitT, hitNormal
            );
        }
    }
#endif
    if (hitT != noHitT) hitNormal = _voxel_unrotateBlockModelVector(rotation, hitNormal);
    return hitT != noHitT;
}

#endif
