#define saturate(x) clamp(x, 0.0, 1.0)
ivec2 _textile_texelToTexel(ivec2 texelPos, ivec2 tileOffset, ivec2 tileSize) {
    return clamp(texelPos, ivec2(0), tileSize - 1) + tileOffset;
}

vec2 _textile_uvToUV(vec2 uv, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(uv * tileSizeF, vec2(0.5), tileSizeF - 0.5) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}

vec2 _textile_uvToGatherUV(vec2 uv, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(uv * tileSizeF, vec2(1.0), tileSizeF - 1.0) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}

vec2 _textile_texelToGatherUV(vec2 texelPos, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(texelPos, vec2(1.0), tileSizeF - 1.0) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}
#undef saturate

#define _RGBA32UI_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(2, 3))
#define _RGBA32UI_ATLAS_SIZE (uval_mainImageSize * vec2(2, 3))
#define _RGBA32UI_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA32UI_ATLAS_SIZE)
#define _RGBA32UI_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA32UI_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA32UI_0_SIZE uval_mainImageSizeI
#define _RGBA32UI_0_SIZE_F uval_mainImageSize
#define _RGBA32UI_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_0_OFFSET, _RGBA32UI_0_SIZE)
#define _RGBA32UI_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA32UI_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA32UI_1_SIZE uval_mainImageSizeI
#define _RGBA32UI_1_SIZE_F uval_mainImageSize
#define _RGBA32UI_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_1_OFFSET, _RGBA32UI_1_SIZE)
#define _RGBA32UI_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA32UI_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA32UI_2_SIZE uval_mainImageSizeI
#define _RGBA32UI_2_SIZE_F uval_mainImageSize
#define _RGBA32UI_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_2_OFFSET, _RGBA32UI_2_SIZE)
#define _RGBA32UI_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA32UI_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA32UI_3_SIZE uval_mainImageSizeI
#define _RGBA32UI_3_SIZE_F uval_mainImageSize
#define _RGBA32UI_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_3_OFFSET, _RGBA32UI_3_SIZE)
#define _RGBA32UI_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_OFFSET (uval_mainImageSizeI * ivec2(0, 2))
#define _RGBA32UI_4_OFFSET_F (uval_mainImageSize * vec2(0, 2))
#define _RGBA32UI_4_SIZE uval_mainImageSizeI
#define _RGBA32UI_4_SIZE_F uval_mainImageSize
#define _RGBA32UI_4_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_4_OFFSET, _RGBA32UI_4_SIZE)
#define _RGBA32UI_4_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_OFFSET (uval_mainImageSizeI * ivec2(1, 2))
#define _RGBA32UI_5_OFFSET_F (uval_mainImageSize * vec2(1, 2))
#define _RGBA32UI_5_SIZE uval_mainImageSizeI
#define _RGBA32UI_5_SIZE_F uval_mainImageSize
#define _RGBA32UI_5_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_5_OFFSET, _RGBA32UI_5_SIZE)
#define _RGBA32UI_5_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define history_gi_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define history_gi_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define history_gi_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define history_gi_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_sample(x) texture(usam_rgba32ui, _RGBA32UI_1_UV_TO_UV(x))
#define history_lowCloud_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_1_UV_TO_GATHER_UV(x), c)
#define history_lowCloud_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_1_TEXEL_TO_GATHER_UV(x), c)
#define history_lowCloud_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), 0)
#define history_lowCloud_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x))
#define history_lowCloud_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoir1_sample(x) texture(usam_rgba32ui, _RGBA32UI_2_UV_TO_UV(x))
#define history_restir_reservoir1_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_2_UV_TO_GATHER_UV(x), c)
#define history_restir_reservoir1_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_2_TEXEL_TO_GATHER_UV(x), c)
#define history_restir_reservoir1_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), 0)
#define history_restir_reservoir1_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x))
#define history_restir_reservoir1_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoir2_sample(x) texture(usam_rgba32ui, _RGBA32UI_3_UV_TO_UV(x))
#define history_restir_reservoir2_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_3_UV_TO_GATHER_UV(x), c)
#define history_restir_reservoir2_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_3_TEXEL_TO_GATHER_UV(x), c)
#define history_restir_reservoir2_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), 0)
#define history_restir_reservoir2_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x))
#define history_restir_reservoir2_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_sample(x) texture(usam_rgba32ui, _RGBA32UI_4_UV_TO_UV(x))
#define transient_gi_diffuse_reprojInfo_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_UV_TO_GATHER_UV(x), c)
#define transient_gi_diffuse_reprojInfo_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_diffuse_reprojInfo_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_diffuse_reprojInfo_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x))
#define transient_gi_diffuse_reprojInfo_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_sample(x) texture(usam_rgba32ui, _RGBA32UI_5_UV_TO_UV(x))
#define transient_lowCloudRender_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_UV_TO_GATHER_UV(x), c)
#define transient_lowCloudRender_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_lowCloudRender_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), 0)
#define transient_lowCloudRender_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x))
#define transient_lowCloudRender_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define transient_lowCloudAccumulated_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_lowCloudAccumulated_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_lowCloudAccumulated_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_lowCloudAccumulated_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define transient_lowCloudAccumulated_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define transient_restir_initialSample_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_restir_initialSample_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_restir_initialSample_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_restir_initialSample_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define transient_restir_initialSample_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_sample(x) texture(usam_rgba32ui, _RGBA32UI_5_UV_TO_UV(x))
#define transient_restir_spatialInput_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_UV_TO_GATHER_UV(x), c)
#define transient_restir_spatialInput_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_restir_spatialInput_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), 0)
#define transient_restir_spatialInput_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x))
#define transient_restir_spatialInput_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define _RGBA16F_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(3, 4))
#define _RGBA16F_ATLAS_SIZE (uval_mainImageSize * vec2(3, 4))
#define _RGBA16F_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA16F_ATLAS_SIZE)
#define _RGBA16F_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA16F_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA16F_0_SIZE uval_mainImageSizeI
#define _RGBA16F_0_SIZE_F uval_mainImageSize
#define _RGBA16F_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_0_OFFSET, _RGBA16F_0_SIZE)
#define _RGBA16F_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA16F_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA16F_1_SIZE uval_mainImageSizeI
#define _RGBA16F_1_SIZE_F uval_mainImageSize
#define _RGBA16F_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_1_OFFSET, _RGBA16F_1_SIZE)
#define _RGBA16F_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA16F_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA16F_2_SIZE uval_mainImageSizeI
#define _RGBA16F_2_SIZE_F uval_mainImageSize
#define _RGBA16F_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_2_OFFSET, _RGBA16F_2_SIZE)
#define _RGBA16F_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA16F_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA16F_3_SIZE uval_mainImageSizeI
#define _RGBA16F_3_SIZE_F uval_mainImageSize
#define _RGBA16F_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_3_OFFSET, _RGBA16F_3_SIZE)
#define _RGBA16F_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_OFFSET (uval_mainImageSizeI * ivec2(0, 2))
#define _RGBA16F_4_OFFSET_F (uval_mainImageSize * vec2(0, 2))
#define _RGBA16F_4_SIZE uval_mainImageSizeI
#define _RGBA16F_4_SIZE_F uval_mainImageSize
#define _RGBA16F_4_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_4_OFFSET, _RGBA16F_4_SIZE)
#define _RGBA16F_4_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_OFFSET (uval_mainImageSizeI * ivec2(1, 2))
#define _RGBA16F_5_OFFSET_F (uval_mainImageSize * vec2(1, 2))
#define _RGBA16F_5_SIZE uval_mainImageSizeI
#define _RGBA16F_5_SIZE_F uval_mainImageSize
#define _RGBA16F_5_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_5_OFFSET, _RGBA16F_5_SIZE)
#define _RGBA16F_5_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_OFFSET (uval_mainImageSizeI * ivec2(2, 0))
#define _RGBA16F_6_OFFSET_F (uval_mainImageSize * vec2(2, 0))
#define _RGBA16F_6_SIZE uval_mainImageSizeI
#define _RGBA16F_6_SIZE_F uval_mainImageSize
#define _RGBA16F_6_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_6_OFFSET, _RGBA16F_6_SIZE)
#define _RGBA16F_6_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_OFFSET (uval_mainImageSizeI * ivec2(2, 1))
#define _RGBA16F_7_OFFSET_F (uval_mainImageSize * vec2(2, 1))
#define _RGBA16F_7_SIZE uval_mainImageSizeI
#define _RGBA16F_7_SIZE_F uval_mainImageSize
#define _RGBA16F_7_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_7_OFFSET, _RGBA16F_7_SIZE)
#define _RGBA16F_7_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_OFFSET (uval_mainImageSizeI * ivec2(2, 2))
#define _RGBA16F_8_OFFSET_F (uval_mainImageSize * vec2(2, 2))
#define _RGBA16F_8_SIZE uval_mainImageSizeI
#define _RGBA16F_8_SIZE_F uval_mainImageSize
#define _RGBA16F_8_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_8_OFFSET, _RGBA16F_8_SIZE)
#define _RGBA16F_8_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_OFFSET (uval_mainImageSizeI * ivec2(0, 3))
#define _RGBA16F_9_OFFSET_F (uval_mainImageSize * vec2(0, 3))
#define _RGBA16F_9_SIZE uval_mainImageSizeI
#define _RGBA16F_9_SIZE_F uval_mainImageSize
#define _RGBA16F_9_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_9_OFFSET, _RGBA16F_9_SIZE)
#define _RGBA16F_9_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define history_gi1_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define history_gi1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define history_gi1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define history_gi1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi2_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define history_gi2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define history_gi2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define history_gi2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define history_gi2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define history_gi2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi3_sample(x) texture(usam_rgba16f, _RGBA16F_2_UV_TO_UV(x))
#define history_gi3_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_2_UV_TO_GATHER_UV(x), c)
#define history_gi3_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_2_TEXEL_TO_GATHER_UV(x), c)
#define history_gi3_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), 0)
#define history_gi3_load(x) imageLoad(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x))
#define history_gi3_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi4_sample(x) texture(usam_rgba16f, _RGBA16F_3_UV_TO_UV(x))
#define history_gi4_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_3_UV_TO_GATHER_UV(x), c)
#define history_gi4_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_3_TEXEL_TO_GATHER_UV(x), c)
#define history_gi4_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), 0)
#define history_gi4_load(x) imageLoad(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x))
#define history_gi4_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_4_UV_TO_UV(x))
#define transient_gi1Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_4_UV_TO_GATHER_UV(x), c)
#define transient_gi1Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi1Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), 0)
#define transient_gi1Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x))
#define transient_gi1Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_5_UV_TO_UV(x))
#define transient_gi2Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_5_UV_TO_GATHER_UV(x), c)
#define transient_gi2Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi2Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), 0)
#define transient_gi2Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x))
#define transient_gi2Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_6_UV_TO_UV(x))
#define transient_gi3Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_6_UV_TO_GATHER_UV(x), c)
#define transient_gi3Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_6_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi3Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), 0)
#define transient_gi3Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x))
#define transient_gi3Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_7_UV_TO_UV(x))
#define transient_gi4Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_7_UV_TO_GATHER_UV(x), c)
#define transient_gi4Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_7_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi4Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), 0)
#define transient_gi4Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x))
#define transient_gi4Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define transient_shadow_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define transient_shadow_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_shadow_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define transient_shadow_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define transient_shadow_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define transient_giRadianceInput_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define transient_giRadianceInput_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_giRadianceInput_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_giRadianceInput_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define transient_giRadianceInput_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define transient_ssgiOut_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define transient_ssgiOut_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_ssgiOut_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define transient_ssgiOut_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define transient_ssgiOut_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_sample(x) texture(usam_rgba16f, _RGBA16F_8_UV_TO_UV(x))
#define transient_gi_blurDiff1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_8_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_8_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurDiff1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x))
#define transient_gi_blurDiff1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_sample(x) texture(usam_rgba16f, _RGBA16F_9_UV_TO_UV(x))
#define transient_gi_blurSpec1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_9_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_9_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurSpec1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x))
#define transient_gi_blurSpec1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define transient_gi_blurDiff2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurDiff2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define transient_gi_blurDiff2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define transient_gi_blurSpec2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurSpec2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define transient_gi_blurSpec2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_sample(x) texture(usam_rgba16f, _RGBA16F_4_UV_TO_UV(x))
#define transient_translucentReflection_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_4_UV_TO_GATHER_UV(x), c)
#define transient_translucentReflection_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_translucentReflection_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), 0)
#define transient_translucentReflection_load(x) imageLoad(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x))
#define transient_translucentReflection_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_sample(x) texture(usam_rgba16f, _RGBA16F_5_UV_TO_UV(x))
#define transient_translucentRefraction_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_5_UV_TO_GATHER_UV(x), c)
#define transient_translucentRefraction_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_translucentRefraction_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), 0)
#define transient_translucentRefraction_load(x) imageLoad(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x))
#define transient_translucentRefraction_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_sample(x) texture(usam_rgba16f, _RGBA16F_4_UV_TO_UV(x))
#define transient_dofInput_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_4_UV_TO_GATHER_UV(x), c)
#define transient_dofInput_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_dofInput_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), 0)
#define transient_dofInput_load(x) imageLoad(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x))
#define transient_dofInput_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define transient_bloom_sample(x) texture(usam_rgba16f, _RGBA16F_4_UV_TO_UV(x))
#define transient_bloom_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_4_UV_TO_GATHER_UV(x), c)
#define transient_bloom_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_bloom_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), 0)
#define transient_bloom_load(x) imageLoad(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x))
#define transient_bloom_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define _RGB10_A2_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(1, 2))
#define _RGB10_A2_ATLAS_SIZE (uval_mainImageSize * vec2(1, 2))
#define _RGB10_A2_ATLAS_SIZE_RCP (vec2(1.0) / _RGB10_A2_ATLAS_SIZE)
#define _RGB10_A2_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGB10_A2_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGB10_A2_0_SIZE uval_mainImageSizeI
#define _RGB10_A2_0_SIZE_F uval_mainImageSize
#define _RGB10_A2_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGB10_A2_0_OFFSET, _RGB10_A2_0_SIZE)
#define _RGB10_A2_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGB10_A2_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGB10_A2_1_SIZE uval_mainImageSizeI
#define _RGB10_A2_1_SIZE_F uval_mainImageSize
#define _RGB10_A2_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGB10_A2_1_OFFSET, _RGB10_A2_1_SIZE)
#define _RGB10_A2_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define history_geomViewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_0_UV_TO_UV(x))
#define history_geomViewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_UV_TO_GATHER_UV(x), c)
#define history_geomViewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_GATHER_UV(x), c)
#define history_geomViewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), 0)
#define history_geomViewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x))
#define history_geomViewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_1_UV_TO_UV(x))
#define history_viewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_UV_TO_GATHER_UV(x), c)
#define history_viewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_GATHER_UV(x), c)
#define history_viewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), 0)
#define history_viewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x))
#define history_viewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_0_UV_TO_UV(x))
#define transient_geomViewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_UV_TO_GATHER_UV(x), c)
#define transient_geomViewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_geomViewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), 0)
#define transient_geomViewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x))
#define transient_geomViewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_1_UV_TO_UV(x))
#define transient_viewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_UV_TO_GATHER_UV(x), c)
#define transient_viewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_viewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), 0)
#define transient_viewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x))
#define transient_viewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define _RGBA8_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(2, 2))
#define _RGBA8_ATLAS_SIZE (uval_mainImageSize * vec2(2, 2))
#define _RGBA8_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA8_ATLAS_SIZE)
#define _RGBA8_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA8_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA8_0_SIZE uval_mainImageSizeI
#define _RGBA8_0_SIZE_F uval_mainImageSize
#define _RGBA8_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_0_OFFSET, _RGBA8_0_SIZE)
#define _RGBA8_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA8_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA8_1_SIZE uval_mainImageSizeI
#define _RGBA8_1_SIZE_F uval_mainImageSize
#define _RGBA8_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_1_OFFSET, _RGBA8_1_SIZE)
#define _RGBA8_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA8_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA8_2_SIZE uval_mainImageSizeI
#define _RGBA8_2_SIZE_F uval_mainImageSize
#define _RGBA8_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_2_OFFSET, _RGBA8_2_SIZE)
#define _RGBA8_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA8_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA8_3_SIZE uval_mainImageSizeI
#define _RGBA8_3_SIZE_F uval_mainImageSize
#define _RGBA8_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_3_OFFSET, _RGBA8_3_SIZE)
#define _RGBA8_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define history_gi5_sample(x) texture(usam_rgba8, _RGBA8_0_UV_TO_UV(x))
#define history_gi5_gather(x, c) textureGather(usam_rgba8, _RGBA8_0_UV_TO_GATHER_UV(x), c)
#define history_gi5_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi5_fetch(x) texelFetch(usam_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi5_load(x) imageLoad(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x))
#define history_gi5_store(x, v) imageStore(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_sample(x) texture(usam_rgba8, _RGBA8_1_UV_TO_UV(x))
#define transient_edgeMaskTemp_gather(x, c) textureGather(usam_rgba8, _RGBA8_1_UV_TO_GATHER_UV(x), c)
#define transient_edgeMaskTemp_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_edgeMaskTemp_fetch(x) texelFetch(usam_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), 0)
#define transient_edgeMaskTemp_load(x) imageLoad(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x))
#define transient_edgeMaskTemp_store(x, v) imageStore(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_sample(x) texture(usam_rgba8, _RGBA8_2_UV_TO_UV(x))
#define transient_edgeMask_gather(x, c) textureGather(usam_rgba8, _RGBA8_2_UV_TO_GATHER_UV(x), c)
#define transient_edgeMask_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_2_TEXEL_TO_GATHER_UV(x), c)
#define transient_edgeMask_fetch(x) texelFetch(usam_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), 0)
#define transient_edgeMask_load(x) imageLoad(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x))
#define transient_edgeMask_store(x, v) imageStore(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_sample(x) texture(usam_rgba8, _RGBA8_3_UV_TO_UV(x))
#define transient_gi5Reprojected_gather(x, c) textureGather(usam_rgba8, _RGBA8_3_UV_TO_GATHER_UV(x), c)
#define transient_gi5Reprojected_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_3_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi5Reprojected_fetch(x) texelFetch(usam_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), 0)
#define transient_gi5Reprojected_load(x) imageLoad(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x))
#define transient_gi5Reprojected_store(x, v) imageStore(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define _RG32UI_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(1, 1))
#define _RG32UI_ATLAS_SIZE (uval_mainImageSize * vec2(1, 1))
#define _RG32UI_ATLAS_SIZE_RCP (vec2(1.0) / _RG32UI_ATLAS_SIZE)
#define _RG32UI_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RG32UI_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RG32UI_0_SIZE uval_mainImageSizeI
#define _RG32UI_0_SIZE_F uval_mainImageSize
#define _RG32UI_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RG32UI_0_OFFSET, _RG32UI_0_SIZE)
#define _RG32UI_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RG32UI_0_OFFSET_F, _RG32UI_0_SIZE_F, _RG32UI_ATLAS_SIZE_RCP)
#define _RG32UI_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RG32UI_0_OFFSET_F, _RG32UI_0_SIZE_F, _RG32UI_ATLAS_SIZE_RCP)
#define _RG32UI_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RG32UI_0_OFFSET_F, _RG32UI_0_SIZE_F, _RG32UI_ATLAS_SIZE_RCP)
#define transient_packedZN_sample(x) texture(usam_rg32ui, _RG32UI_0_UV_TO_UV(x))
#define transient_packedZN_gather(x, c) textureGather(usam_rg32ui, _RG32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_packedZN_gatherTexel(x, c) textureGather(usam_rg32ui, _RG32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_packedZN_fetch(x) texelFetch(usam_rg32ui, _RG32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_packedZN_load(x) imageLoad(uimg_rg32ui, _RG32UI_0_TEXEL_TO_TEXEL(x))
#define transient_packedZN_store(x, v) imageStore(uimg_rg32ui, _RG32UI_0_TEXEL_TO_TEXEL(x), v)
#define _R32UI_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(1, 1))
#define _R32UI_ATLAS_SIZE (uval_mainImageSize * vec2(1, 1))
#define _R32UI_ATLAS_SIZE_RCP (vec2(1.0) / _R32UI_ATLAS_SIZE)
#define _R32UI_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _R32UI_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _R32UI_0_SIZE uval_mainImageSizeI
#define _R32UI_0_SIZE_F uval_mainImageSize
#define _R32UI_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _R32UI_0_OFFSET, _R32UI_0_SIZE)
#define _R32UI_0_UV_TO_UV(uv) _textile_uvToUV(uv, _R32UI_0_OFFSET_F, _R32UI_0_SIZE_F, _R32UI_ATLAS_SIZE_RCP)
#define _R32UI_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _R32UI_0_OFFSET_F, _R32UI_0_SIZE_F, _R32UI_ATLAS_SIZE_RCP)
#define _R32UI_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _R32UI_0_OFFSET_F, _R32UI_0_SIZE_F, _R32UI_ATLAS_SIZE_RCP)
#define transient_geometryNormal_sample(x) texture(usam_r32ui, _R32UI_0_UV_TO_UV(x))
#define transient_geometryNormal_gather(x, c) textureGather(usam_r32ui, _R32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_geometryNormal_gatherTexel(x, c) textureGather(usam_r32ui, _R32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_geometryNormal_fetch(x) texelFetch(usam_r32ui, _R32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_geometryNormal_load(x) imageLoad(uimg_r32ui, _R32UI_0_TEXEL_TO_TEXEL(x))
#define transient_geometryNormal_store(x, v) imageStore(uimg_r32ui, _R32UI_0_TEXEL_TO_TEXEL(x), v)
#define _R32F_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(1, 1))
#define _R32F_ATLAS_SIZE (uval_mainImageSize * vec2(1, 1))
#define _R32F_ATLAS_SIZE_RCP (vec2(1.0) / _R32F_ATLAS_SIZE)
#define _R32F_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _R32F_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _R32F_0_SIZE uval_mainImageSizeI
#define _R32F_0_SIZE_F uval_mainImageSize
#define _R32F_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _R32F_0_OFFSET, _R32F_0_SIZE)
#define _R32F_0_UV_TO_UV(uv) _textile_uvToUV(uv, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define history_viewZ_sample(x) texture(usam_r32f, _R32F_0_UV_TO_UV(x))
#define history_viewZ_gather(x, c) textureGather(usam_r32f, _R32F_0_UV_TO_GATHER_UV(x), c)
#define history_viewZ_gatherTexel(x, c) textureGather(usam_r32f, _R32F_0_TEXEL_TO_GATHER_UV(x), c)
#define history_viewZ_fetch(x) texelFetch(usam_r32f, _R32F_0_TEXEL_TO_TEXEL(x), 0)
#define history_viewZ_load(x) imageLoad(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x))
#define history_viewZ_store(x, v) imageStore(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
