#define saturate(x) clamp(x, 0.0, 1.0)
ivec2 _textile_texelToTexel(ivec2 texelPos, ivec2 tileOffset, ivec2 tileSize) {
    return clamp(texelPos, ivec2(0), tileSize - 1) + tileOffset;
}

vec2 _textile_uvToUV(vec2 uv, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(uv * tileSizeF, vec2(0.5), tileSizeF - 0.5) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}

vec2 _textile_uvToGatherUV(vec2 uv, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(uv * tileSizeF, vec2(1.0), tileSizeF - 1.0) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}

vec2 _textile_texelToGatherUV(vec2 texelPos, vec2 tileOffsetF, vec2 tileSizeF, vec2 atlastSizeRcp) {
    vec2 textureTexelPos = clamp(texelPos, vec2(1.0), tileSizeF - 1.0) + tileOffsetF;
    return saturate(textureTexelPos * atlastSizeRcp);
}
#undef saturate

#define _RGBA32UI_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(3, 3))
#define _RGBA32UI_ATLAS_SIZE (uval_mainImageSize * vec2(3, 3))
#define _RGBA32UI_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA32UI_ATLAS_SIZE)
#define _RGBA32UI_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA32UI_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA32UI_0_SIZE uval_mainImageSizeI
#define _RGBA32UI_0_SIZE_F uval_mainImageSize
#define _RGBA32UI_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_0_OFFSET, _RGBA32UI_0_SIZE)
#define _RGBA32UI_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_0_OFFSET_F, _RGBA32UI_0_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA32UI_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA32UI_1_SIZE uval_mainImageSizeI
#define _RGBA32UI_1_SIZE_F uval_mainImageSize
#define _RGBA32UI_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_1_OFFSET, _RGBA32UI_1_SIZE)
#define _RGBA32UI_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_1_OFFSET_F, _RGBA32UI_1_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA32UI_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA32UI_2_SIZE uval_mainImageSizeI
#define _RGBA32UI_2_SIZE_F uval_mainImageSize
#define _RGBA32UI_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_2_OFFSET, _RGBA32UI_2_SIZE)
#define _RGBA32UI_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_2_OFFSET_F, _RGBA32UI_2_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA32UI_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA32UI_3_SIZE uval_mainImageSizeI
#define _RGBA32UI_3_SIZE_F uval_mainImageSize
#define _RGBA32UI_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_3_OFFSET, _RGBA32UI_3_SIZE)
#define _RGBA32UI_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_3_OFFSET_F, _RGBA32UI_3_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_OFFSET (uval_mainImageSizeI * ivec2(0, 2))
#define _RGBA32UI_4_OFFSET_F (uval_mainImageSize * vec2(0, 2))
#define _RGBA32UI_4_SIZE uval_mainImageSizeI
#define _RGBA32UI_4_SIZE_F uval_mainImageSize
#define _RGBA32UI_4_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_4_OFFSET, _RGBA32UI_4_SIZE)
#define _RGBA32UI_4_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_4_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_4_OFFSET_F, _RGBA32UI_4_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_OFFSET (uval_mainImageSizeI * ivec2(1, 2))
#define _RGBA32UI_5_OFFSET_F (uval_mainImageSize * vec2(1, 2))
#define _RGBA32UI_5_SIZE uval_mainImageSizeI
#define _RGBA32UI_5_SIZE_F uval_mainImageSize
#define _RGBA32UI_5_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_5_OFFSET, _RGBA32UI_5_SIZE)
#define _RGBA32UI_5_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_5_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_5_OFFSET_F, _RGBA32UI_5_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_6_OFFSET (uval_mainImageSizeI * ivec2(2, 0))
#define _RGBA32UI_6_OFFSET_F (uval_mainImageSize * vec2(2, 0))
#define _RGBA32UI_6_SIZE uval_mainImageSizeI
#define _RGBA32UI_6_SIZE_F uval_mainImageSize
#define _RGBA32UI_6_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA32UI_6_OFFSET, _RGBA32UI_6_SIZE)
#define _RGBA32UI_6_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA32UI_6_OFFSET_F, _RGBA32UI_6_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_6_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA32UI_6_OFFSET_F, _RGBA32UI_6_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define _RGBA32UI_6_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA32UI_6_OFFSET_F, _RGBA32UI_6_SIZE_F, _RGBA32UI_ATLAS_SIZE_RCP)
#define history_gi_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define history_gi_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define history_gi_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define history_gi_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define history_gi_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v1, v2)
#define history_lowCloud_sample(x) texture(usam_rgba32ui, _RGBA32UI_1_UV_TO_UV(x))
#define history_lowCloud_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_1_UV_TO_GATHER_UV(x), c)
#define history_lowCloud_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_1_TEXEL_TO_GATHER_UV(x), c)
#define history_lowCloud_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), 0)
#define history_lowCloud_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x))
#define history_lowCloud_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v)
#define history_lowCloud_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_1_TEXEL_TO_TEXEL(x), v1, v2)
#define history_restir_reservoirTemporal_sample(x) texture(usam_rgba32ui, _RGBA32UI_2_UV_TO_UV(x))
#define history_restir_reservoirTemporal_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_2_UV_TO_GATHER_UV(x), c)
#define history_restir_reservoirTemporal_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_2_TEXEL_TO_GATHER_UV(x), c)
#define history_restir_reservoirTemporal_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), 0)
#define history_restir_reservoirTemporal_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x))
#define history_restir_reservoirTemporal_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirTemporal_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_2_TEXEL_TO_TEXEL(x), v1, v2)
#define history_restir_reservoirSpatial_sample(x) texture(usam_rgba32ui, _RGBA32UI_3_UV_TO_UV(x))
#define history_restir_reservoirSpatial_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_3_UV_TO_GATHER_UV(x), c)
#define history_restir_reservoirSpatial_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_3_TEXEL_TO_GATHER_UV(x), c)
#define history_restir_reservoirSpatial_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), 0)
#define history_restir_reservoirSpatial_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x))
#define history_restir_reservoirSpatial_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v)
#define history_restir_reservoirSpatial_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_3_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_lowCloudRender_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define transient_lowCloudRender_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_lowCloudRender_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_lowCloudRender_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_lowCloudRender_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define transient_lowCloudRender_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudRender_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_lowCloudAccumulated_sample(x) texture(usam_rgba32ui, _RGBA32UI_4_UV_TO_UV(x))
#define transient_lowCloudAccumulated_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_UV_TO_GATHER_UV(x), c)
#define transient_lowCloudAccumulated_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_lowCloudAccumulated_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), 0)
#define transient_lowCloudAccumulated_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x))
#define transient_lowCloudAccumulated_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_lowCloudAccumulated_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi_diffuse_reprojInfo_sample(x) texture(usam_rgba32ui, _RGBA32UI_5_UV_TO_UV(x))
#define transient_gi_diffuse_reprojInfo_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_UV_TO_GATHER_UV(x), c)
#define transient_gi_diffuse_reprojInfo_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_diffuse_reprojInfo_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_diffuse_reprojInfo_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x))
#define transient_gi_diffuse_reprojInfo_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi_diffuse_reprojInfo_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_5_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_restir_initialSample_sample(x) texture(usam_rgba32ui, _RGBA32UI_0_UV_TO_UV(x))
#define transient_restir_initialSample_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_UV_TO_GATHER_UV(x), c)
#define transient_restir_initialSample_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_restir_initialSample_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), 0)
#define transient_restir_initialSample_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x))
#define transient_restir_initialSample_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v)
#define transient_restir_initialSample_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_restir_reservoirReprojected_sample(x) texture(usam_rgba32ui, _RGBA32UI_4_UV_TO_UV(x))
#define transient_restir_reservoirReprojected_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_UV_TO_GATHER_UV(x), c)
#define transient_restir_reservoirReprojected_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_GATHER_UV(x), c)
#define transient_restir_reservoirReprojected_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), 0)
#define transient_restir_reservoirReprojected_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x))
#define transient_restir_reservoirReprojected_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v)
#define transient_restir_reservoirReprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_4_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_restir_spatialInput_sample(x) texture(usam_rgba32ui, _RGBA32UI_6_UV_TO_UV(x))
#define transient_restir_spatialInput_gather(x, c) textureGather(usam_rgba32ui, _RGBA32UI_6_UV_TO_GATHER_UV(x), c)
#define transient_restir_spatialInput_gatherTexel(x, c) textureGather(usam_rgba32ui, _RGBA32UI_6_TEXEL_TO_GATHER_UV(x), c)
#define transient_restir_spatialInput_fetch(x) texelFetch(usam_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), 0)
#define transient_restir_spatialInput_load(x) imageLoad(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x))
#define transient_restir_spatialInput_store(x, v) imageStore(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicAdd(x, v) imageAtomicAdd(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicMin(x, v) imageAtomicMin(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicMax(x, v) imageAtomicMax(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicAnd(x, v) imageAtomicAnd(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicOr(x, v) imageAtomicOr(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicXor(x, v) imageAtomicXor(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicExchange(x, v) imageAtomicExchange(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v)
#define transient_restir_spatialInput_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba32ui, _RGBA32UI_6_TEXEL_TO_TEXEL(x), v1, v2)
#define _RGBA16F_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(3, 4))
#define _RGBA16F_ATLAS_SIZE (uval_mainImageSize * vec2(3, 4))
#define _RGBA16F_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA16F_ATLAS_SIZE)
#define _RGBA16F_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA16F_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA16F_0_SIZE uval_mainImageSizeI
#define _RGBA16F_0_SIZE_F uval_mainImageSize
#define _RGBA16F_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_0_OFFSET, _RGBA16F_0_SIZE)
#define _RGBA16F_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_0_OFFSET_F, _RGBA16F_0_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA16F_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA16F_1_SIZE uval_mainImageSizeI
#define _RGBA16F_1_SIZE_F uval_mainImageSize
#define _RGBA16F_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_1_OFFSET, _RGBA16F_1_SIZE)
#define _RGBA16F_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_1_OFFSET_F, _RGBA16F_1_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA16F_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA16F_2_SIZE uval_mainImageSizeI
#define _RGBA16F_2_SIZE_F uval_mainImageSize
#define _RGBA16F_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_2_OFFSET, _RGBA16F_2_SIZE)
#define _RGBA16F_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_2_OFFSET_F, _RGBA16F_2_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA16F_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA16F_3_SIZE uval_mainImageSizeI
#define _RGBA16F_3_SIZE_F uval_mainImageSize
#define _RGBA16F_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_3_OFFSET, _RGBA16F_3_SIZE)
#define _RGBA16F_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_3_OFFSET_F, _RGBA16F_3_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_OFFSET (uval_mainImageSizeI * ivec2(0, 2))
#define _RGBA16F_4_OFFSET_F (uval_mainImageSize * vec2(0, 2))
#define _RGBA16F_4_SIZE uval_mainImageSizeI
#define _RGBA16F_4_SIZE_F uval_mainImageSize
#define _RGBA16F_4_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_4_OFFSET, _RGBA16F_4_SIZE)
#define _RGBA16F_4_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_4_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_4_OFFSET_F, _RGBA16F_4_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_OFFSET (uval_mainImageSizeI * ivec2(1, 2))
#define _RGBA16F_5_OFFSET_F (uval_mainImageSize * vec2(1, 2))
#define _RGBA16F_5_SIZE uval_mainImageSizeI
#define _RGBA16F_5_SIZE_F uval_mainImageSize
#define _RGBA16F_5_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_5_OFFSET, _RGBA16F_5_SIZE)
#define _RGBA16F_5_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_5_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_5_OFFSET_F, _RGBA16F_5_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_OFFSET (uval_mainImageSizeI * ivec2(2, 0))
#define _RGBA16F_6_OFFSET_F (uval_mainImageSize * vec2(2, 0))
#define _RGBA16F_6_SIZE uval_mainImageSizeI
#define _RGBA16F_6_SIZE_F uval_mainImageSize
#define _RGBA16F_6_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_6_OFFSET, _RGBA16F_6_SIZE)
#define _RGBA16F_6_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_6_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_6_OFFSET_F, _RGBA16F_6_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_OFFSET (uval_mainImageSizeI * ivec2(2, 1))
#define _RGBA16F_7_OFFSET_F (uval_mainImageSize * vec2(2, 1))
#define _RGBA16F_7_SIZE uval_mainImageSizeI
#define _RGBA16F_7_SIZE_F uval_mainImageSize
#define _RGBA16F_7_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_7_OFFSET, _RGBA16F_7_SIZE)
#define _RGBA16F_7_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_7_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_7_OFFSET_F, _RGBA16F_7_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_OFFSET (uval_mainImageSizeI * ivec2(2, 2))
#define _RGBA16F_8_OFFSET_F (uval_mainImageSize * vec2(2, 2))
#define _RGBA16F_8_SIZE uval_mainImageSizeI
#define _RGBA16F_8_SIZE_F uval_mainImageSize
#define _RGBA16F_8_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_8_OFFSET, _RGBA16F_8_SIZE)
#define _RGBA16F_8_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_8_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_8_OFFSET_F, _RGBA16F_8_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_OFFSET (uval_mainImageSizeI * ivec2(0, 3))
#define _RGBA16F_9_OFFSET_F (uval_mainImageSize * vec2(0, 3))
#define _RGBA16F_9_SIZE uval_mainImageSizeI
#define _RGBA16F_9_SIZE_F uval_mainImageSize
#define _RGBA16F_9_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_9_OFFSET, _RGBA16F_9_SIZE)
#define _RGBA16F_9_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_9_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_9_OFFSET_F, _RGBA16F_9_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_10_OFFSET (uval_mainImageSizeI * ivec2(1, 3))
#define _RGBA16F_10_OFFSET_F (uval_mainImageSize * vec2(1, 3))
#define _RGBA16F_10_SIZE uval_mainImageSizeI
#define _RGBA16F_10_SIZE_F uval_mainImageSize
#define _RGBA16F_10_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_10_OFFSET, _RGBA16F_10_SIZE)
#define _RGBA16F_10_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_10_OFFSET_F, _RGBA16F_10_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_10_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_10_OFFSET_F, _RGBA16F_10_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_10_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_10_OFFSET_F, _RGBA16F_10_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_11_OFFSET (uval_mainImageSizeI * ivec2(2, 3))
#define _RGBA16F_11_OFFSET_F (uval_mainImageSize * vec2(2, 3))
#define _RGBA16F_11_SIZE uval_mainImageSizeI
#define _RGBA16F_11_SIZE_F uval_mainImageSize
#define _RGBA16F_11_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA16F_11_OFFSET, _RGBA16F_11_SIZE)
#define _RGBA16F_11_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA16F_11_OFFSET_F, _RGBA16F_11_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_11_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA16F_11_OFFSET_F, _RGBA16F_11_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define _RGBA16F_11_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA16F_11_OFFSET_F, _RGBA16F_11_SIZE_F, _RGBA16F_ATLAS_SIZE_RCP)
#define history_gi1_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define history_gi1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define history_gi1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define history_gi1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define history_gi1_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v1, v2)
#define history_gi2_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define history_gi2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define history_gi2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define history_gi2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define history_gi2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define history_gi2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define history_gi2_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v1, v2)
#define history_gi3_sample(x) texture(usam_rgba16f, _RGBA16F_2_UV_TO_UV(x))
#define history_gi3_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_2_UV_TO_GATHER_UV(x), c)
#define history_gi3_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_2_TEXEL_TO_GATHER_UV(x), c)
#define history_gi3_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), 0)
#define history_gi3_load(x) imageLoad(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x))
#define history_gi3_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define history_gi3_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v1, v2)
#define history_gi4_sample(x) texture(usam_rgba16f, _RGBA16F_3_UV_TO_UV(x))
#define history_gi4_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_3_UV_TO_GATHER_UV(x), c)
#define history_gi4_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_3_TEXEL_TO_GATHER_UV(x), c)
#define history_gi4_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), 0)
#define history_gi4_load(x) imageLoad(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x))
#define history_gi4_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v)
#define history_gi4_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_3_TEXEL_TO_TEXEL(x), v1, v2)
#define history_gi_diffuse_shading_sample(x) texture(usam_rgba16f, _RGBA16F_4_UV_TO_UV(x))
#define history_gi_diffuse_shading_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_4_UV_TO_GATHER_UV(x), c)
#define history_gi_diffuse_shading_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_4_TEXEL_TO_GATHER_UV(x), c)
#define history_gi_diffuse_shading_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), 0)
#define history_gi_diffuse_shading_load(x) imageLoad(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x))
#define history_gi_diffuse_shading_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v)
#define history_gi_diffuse_shading_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_4_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi1Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_5_UV_TO_UV(x))
#define transient_gi1Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_5_UV_TO_GATHER_UV(x), c)
#define transient_gi1Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi1Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), 0)
#define transient_gi1Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x))
#define transient_gi1Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_gi1Reprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi2Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_6_UV_TO_UV(x))
#define transient_gi2Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_6_UV_TO_GATHER_UV(x), c)
#define transient_gi2Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_6_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi2Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), 0)
#define transient_gi2Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x))
#define transient_gi2Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_gi2Reprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi3Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_7_UV_TO_UV(x))
#define transient_gi3Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_7_UV_TO_GATHER_UV(x), c)
#define transient_gi3Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_7_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi3Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), 0)
#define transient_gi3Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x))
#define transient_gi3Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v)
#define transient_gi3Reprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_7_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi4Reprojected_sample(x) texture(usam_rgba16f, _RGBA16F_8_UV_TO_UV(x))
#define transient_gi4Reprojected_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_8_UV_TO_GATHER_UV(x), c)
#define transient_gi4Reprojected_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_8_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi4Reprojected_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), 0)
#define transient_gi4Reprojected_load(x) imageLoad(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x))
#define transient_gi4Reprojected_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v)
#define transient_gi4Reprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_8_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_shadow_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define transient_shadow_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define transient_shadow_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_shadow_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define transient_shadow_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define transient_shadow_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_shadow_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_giRadianceInput1_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define transient_giRadianceInput1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define transient_giRadianceInput1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_giRadianceInput1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_giRadianceInput1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define transient_giRadianceInput1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput1_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_giRadianceInput2_sample(x) texture(usam_rgba16f, _RGBA16F_2_UV_TO_UV(x))
#define transient_giRadianceInput2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_2_UV_TO_GATHER_UV(x), c)
#define transient_giRadianceInput2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_2_TEXEL_TO_GATHER_UV(x), c)
#define transient_giRadianceInput2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), 0)
#define transient_giRadianceInput2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x))
#define transient_giRadianceInput2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v)
#define transient_giRadianceInput2_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_2_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_ssgiOut_sample(x) texture(usam_rgba16f, _RGBA16F_0_UV_TO_UV(x))
#define transient_ssgiOut_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_0_UV_TO_GATHER_UV(x), c)
#define transient_ssgiOut_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_ssgiOut_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), 0)
#define transient_ssgiOut_load(x) imageLoad(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x))
#define transient_ssgiOut_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v)
#define transient_ssgiOut_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi_blurDiff1_sample(x) texture(usam_rgba16f, _RGBA16F_9_UV_TO_UV(x))
#define transient_gi_blurDiff1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_9_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_9_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurDiff1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x))
#define transient_gi_blurDiff1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff1_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_9_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi_blurSpec1_sample(x) texture(usam_rgba16f, _RGBA16F_1_UV_TO_UV(x))
#define transient_gi_blurSpec1_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_1_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec1_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec1_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurSpec1_load(x) imageLoad(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x))
#define transient_gi_blurSpec1_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec1_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi_blurDiff2_sample(x) texture(usam_rgba16f, _RGBA16F_10_UV_TO_UV(x))
#define transient_gi_blurDiff2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_10_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_10_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurDiff2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurDiff2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x))
#define transient_gi_blurDiff2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurDiff2_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_10_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi_blurSpec2_sample(x) texture(usam_rgba16f, _RGBA16F_11_UV_TO_UV(x))
#define transient_gi_blurSpec2_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_11_UV_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec2_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_11_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi_blurSpec2_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), 0)
#define transient_gi_blurSpec2_load(x) imageLoad(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x))
#define transient_gi_blurSpec2_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v)
#define transient_gi_blurSpec2_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_11_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_translucentReflection_sample(x) texture(usam_rgba16f, _RGBA16F_5_UV_TO_UV(x))
#define transient_translucentReflection_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_5_UV_TO_GATHER_UV(x), c)
#define transient_translucentReflection_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_translucentReflection_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), 0)
#define transient_translucentReflection_load(x) imageLoad(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x))
#define transient_translucentReflection_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_translucentReflection_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_translucentRefraction_sample(x) texture(usam_rgba16f, _RGBA16F_6_UV_TO_UV(x))
#define transient_translucentRefraction_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_6_UV_TO_GATHER_UV(x), c)
#define transient_translucentRefraction_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_6_TEXEL_TO_GATHER_UV(x), c)
#define transient_translucentRefraction_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), 0)
#define transient_translucentRefraction_load(x) imageLoad(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x))
#define transient_translucentRefraction_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v)
#define transient_translucentRefraction_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_6_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_dofInput_sample(x) texture(usam_rgba16f, _RGBA16F_5_UV_TO_UV(x))
#define transient_dofInput_gather(x, c) textureGather(usam_rgba16f, _RGBA16F_5_UV_TO_GATHER_UV(x), c)
#define transient_dofInput_gatherTexel(x, c) textureGather(usam_rgba16f, _RGBA16F_5_TEXEL_TO_GATHER_UV(x), c)
#define transient_dofInput_fetch(x) texelFetch(usam_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), 0)
#define transient_dofInput_load(x) imageLoad(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x))
#define transient_dofInput_store(x, v) imageStore(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicAdd(x, v) imageAtomicAdd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicMin(x, v) imageAtomicMin(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicMax(x, v) imageAtomicMax(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicAnd(x, v) imageAtomicAnd(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicOr(x, v) imageAtomicOr(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicXor(x, v) imageAtomicXor(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicExchange(x, v) imageAtomicExchange(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v)
#define transient_dofInput_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba16f, _RGBA16F_5_TEXEL_TO_TEXEL(x), v1, v2)
#define _RGB10_A2_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(1, 2))
#define _RGB10_A2_ATLAS_SIZE (uval_mainImageSize * vec2(1, 2))
#define _RGB10_A2_ATLAS_SIZE_RCP (vec2(1.0) / _RGB10_A2_ATLAS_SIZE)
#define _RGB10_A2_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGB10_A2_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGB10_A2_0_SIZE uval_mainImageSizeI
#define _RGB10_A2_0_SIZE_F uval_mainImageSize
#define _RGB10_A2_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGB10_A2_0_OFFSET, _RGB10_A2_0_SIZE)
#define _RGB10_A2_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGB10_A2_0_OFFSET_F, _RGB10_A2_0_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGB10_A2_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGB10_A2_1_SIZE uval_mainImageSizeI
#define _RGB10_A2_1_SIZE_F uval_mainImageSize
#define _RGB10_A2_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGB10_A2_1_OFFSET, _RGB10_A2_1_SIZE)
#define _RGB10_A2_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define _RGB10_A2_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGB10_A2_1_OFFSET_F, _RGB10_A2_1_SIZE_F, _RGB10_A2_ATLAS_SIZE_RCP)
#define history_geomViewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_0_UV_TO_UV(x))
#define history_geomViewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_UV_TO_GATHER_UV(x), c)
#define history_geomViewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_GATHER_UV(x), c)
#define history_geomViewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), 0)
#define history_geomViewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x))
#define history_geomViewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicAdd(x, v) imageAtomicAdd(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicMin(x, v) imageAtomicMin(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicMax(x, v) imageAtomicMax(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicAnd(x, v) imageAtomicAnd(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicOr(x, v) imageAtomicOr(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicXor(x, v) imageAtomicXor(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicExchange(x, v) imageAtomicExchange(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define history_geomViewNormal_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v1, v2)
#define history_viewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_1_UV_TO_UV(x))
#define history_viewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_UV_TO_GATHER_UV(x), c)
#define history_viewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_GATHER_UV(x), c)
#define history_viewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), 0)
#define history_viewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x))
#define history_viewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicAdd(x, v) imageAtomicAdd(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicMin(x, v) imageAtomicMin(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicMax(x, v) imageAtomicMax(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicAnd(x, v) imageAtomicAnd(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicOr(x, v) imageAtomicOr(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicXor(x, v) imageAtomicXor(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicExchange(x, v) imageAtomicExchange(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define history_viewNormal_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_geomViewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_0_UV_TO_UV(x))
#define transient_geomViewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_UV_TO_GATHER_UV(x), c)
#define transient_geomViewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_GATHER_UV(x), c)
#define transient_geomViewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), 0)
#define transient_geomViewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x))
#define transient_geomViewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicAdd(x, v) imageAtomicAdd(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicMin(x, v) imageAtomicMin(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicMax(x, v) imageAtomicMax(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicAnd(x, v) imageAtomicAnd(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicOr(x, v) imageAtomicOr(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicXor(x, v) imageAtomicXor(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicExchange(x, v) imageAtomicExchange(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v)
#define transient_geomViewNormal_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgb10_a2, _RGB10_A2_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_viewNormal_sample(x) texture(usam_rgb10_a2, _RGB10_A2_1_UV_TO_UV(x))
#define transient_viewNormal_gather(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_UV_TO_GATHER_UV(x), c)
#define transient_viewNormal_gatherTexel(x, c) textureGather(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_viewNormal_fetch(x) texelFetch(usam_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), 0)
#define transient_viewNormal_load(x) imageLoad(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x))
#define transient_viewNormal_store(x, v) imageStore(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicAdd(x, v) imageAtomicAdd(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicMin(x, v) imageAtomicMin(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicMax(x, v) imageAtomicMax(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicAnd(x, v) imageAtomicAnd(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicOr(x, v) imageAtomicOr(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicXor(x, v) imageAtomicXor(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicExchange(x, v) imageAtomicExchange(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v)
#define transient_viewNormal_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgb10_a2, _RGB10_A2_1_TEXEL_TO_TEXEL(x), v1, v2)
#define _RGBA8_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(2, 2))
#define _RGBA8_ATLAS_SIZE (uval_mainImageSize * vec2(2, 2))
#define _RGBA8_ATLAS_SIZE_RCP (vec2(1.0) / _RGBA8_ATLAS_SIZE)
#define _RGBA8_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _RGBA8_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _RGBA8_0_SIZE uval_mainImageSizeI
#define _RGBA8_0_SIZE_F uval_mainImageSize
#define _RGBA8_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_0_OFFSET, _RGBA8_0_SIZE)
#define _RGBA8_0_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_0_OFFSET_F, _RGBA8_0_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _RGBA8_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _RGBA8_1_SIZE uval_mainImageSizeI
#define _RGBA8_1_SIZE_F uval_mainImageSize
#define _RGBA8_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_1_OFFSET, _RGBA8_1_SIZE)
#define _RGBA8_1_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_1_OFFSET_F, _RGBA8_1_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _RGBA8_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _RGBA8_2_SIZE uval_mainImageSizeI
#define _RGBA8_2_SIZE_F uval_mainImageSize
#define _RGBA8_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_2_OFFSET, _RGBA8_2_SIZE)
#define _RGBA8_2_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_2_OFFSET_F, _RGBA8_2_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_OFFSET (uval_mainImageSizeI * ivec2(1, 1))
#define _RGBA8_3_OFFSET_F (uval_mainImageSize * vec2(1, 1))
#define _RGBA8_3_SIZE uval_mainImageSizeI
#define _RGBA8_3_SIZE_F uval_mainImageSize
#define _RGBA8_3_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _RGBA8_3_OFFSET, _RGBA8_3_SIZE)
#define _RGBA8_3_UV_TO_UV(uv) _textile_uvToUV(uv, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define _RGBA8_3_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _RGBA8_3_OFFSET_F, _RGBA8_3_SIZE_F, _RGBA8_ATLAS_SIZE_RCP)
#define history_gi5_sample(x) texture(usam_rgba8, _RGBA8_0_UV_TO_UV(x))
#define history_gi5_gather(x, c) textureGather(usam_rgba8, _RGBA8_0_UV_TO_GATHER_UV(x), c)
#define history_gi5_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_0_TEXEL_TO_GATHER_UV(x), c)
#define history_gi5_fetch(x) texelFetch(usam_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), 0)
#define history_gi5_load(x) imageLoad(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x))
#define history_gi5_store(x, v) imageStore(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicAdd(x, v) imageAtomicAdd(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicMin(x, v) imageAtomicMin(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicMax(x, v) imageAtomicMax(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicAnd(x, v) imageAtomicAnd(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicOr(x, v) imageAtomicOr(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicXor(x, v) imageAtomicXor(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicExchange(x, v) imageAtomicExchange(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v)
#define history_gi5_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba8, _RGBA8_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_edgeMaskTemp_sample(x) texture(usam_rgba8, _RGBA8_1_UV_TO_UV(x))
#define transient_edgeMaskTemp_gather(x, c) textureGather(usam_rgba8, _RGBA8_1_UV_TO_GATHER_UV(x), c)
#define transient_edgeMaskTemp_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_edgeMaskTemp_fetch(x) texelFetch(usam_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), 0)
#define transient_edgeMaskTemp_load(x) imageLoad(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x))
#define transient_edgeMaskTemp_store(x, v) imageStore(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicAdd(x, v) imageAtomicAdd(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicMin(x, v) imageAtomicMin(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicMax(x, v) imageAtomicMax(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicAnd(x, v) imageAtomicAnd(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicOr(x, v) imageAtomicOr(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicXor(x, v) imageAtomicXor(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicExchange(x, v) imageAtomicExchange(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMaskTemp_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_edgeMask_sample(x) texture(usam_rgba8, _RGBA8_2_UV_TO_UV(x))
#define transient_edgeMask_gather(x, c) textureGather(usam_rgba8, _RGBA8_2_UV_TO_GATHER_UV(x), c)
#define transient_edgeMask_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_2_TEXEL_TO_GATHER_UV(x), c)
#define transient_edgeMask_fetch(x) texelFetch(usam_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), 0)
#define transient_edgeMask_load(x) imageLoad(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x))
#define transient_edgeMask_store(x, v) imageStore(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicAdd(x, v) imageAtomicAdd(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicMin(x, v) imageAtomicMin(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicMax(x, v) imageAtomicMax(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicAnd(x, v) imageAtomicAnd(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicOr(x, v) imageAtomicOr(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicXor(x, v) imageAtomicXor(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicExchange(x, v) imageAtomicExchange(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v)
#define transient_edgeMask_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba8, _RGBA8_2_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_gi5Reprojected_sample(x) texture(usam_rgba8, _RGBA8_3_UV_TO_UV(x))
#define transient_gi5Reprojected_gather(x, c) textureGather(usam_rgba8, _RGBA8_3_UV_TO_GATHER_UV(x), c)
#define transient_gi5Reprojected_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_3_TEXEL_TO_GATHER_UV(x), c)
#define transient_gi5Reprojected_fetch(x) texelFetch(usam_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), 0)
#define transient_gi5Reprojected_load(x) imageLoad(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x))
#define transient_gi5Reprojected_store(x, v) imageStore(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicAdd(x, v) imageAtomicAdd(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicMin(x, v) imageAtomicMin(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicMax(x, v) imageAtomicMax(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicAnd(x, v) imageAtomicAnd(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicOr(x, v) imageAtomicOr(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicXor(x, v) imageAtomicXor(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicExchange(x, v) imageAtomicExchange(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v)
#define transient_gi5Reprojected_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba8, _RGBA8_3_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_solidAlbedo_sample(x) texture(usam_rgba8, _RGBA8_1_UV_TO_UV(x))
#define transient_solidAlbedo_gather(x, c) textureGather(usam_rgba8, _RGBA8_1_UV_TO_GATHER_UV(x), c)
#define transient_solidAlbedo_gatherTexel(x, c) textureGather(usam_rgba8, _RGBA8_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_solidAlbedo_fetch(x) texelFetch(usam_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), 0)
#define transient_solidAlbedo_load(x) imageLoad(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x))
#define transient_solidAlbedo_store(x, v) imageStore(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicAdd(x, v) imageAtomicAdd(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicMin(x, v) imageAtomicMin(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicMax(x, v) imageAtomicMax(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicAnd(x, v) imageAtomicAnd(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicOr(x, v) imageAtomicOr(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicXor(x, v) imageAtomicXor(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicExchange(x, v) imageAtomicExchange(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v)
#define transient_solidAlbedo_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_rgba8, _RGBA8_1_TEXEL_TO_TEXEL(x), v1, v2)
#define _R32F_ATLAS_SIZE_I (uval_mainImageSizeI * ivec2(2, 2))
#define _R32F_ATLAS_SIZE (uval_mainImageSize * vec2(2, 2))
#define _R32F_ATLAS_SIZE_RCP (vec2(1.0) / _R32F_ATLAS_SIZE)
#define _R32F_0_OFFSET (uval_mainImageSizeI * ivec2(0, 0))
#define _R32F_0_OFFSET_F (uval_mainImageSize * vec2(0, 0))
#define _R32F_0_SIZE uval_mainImageSizeI
#define _R32F_0_SIZE_F uval_mainImageSize
#define _R32F_0_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _R32F_0_OFFSET, _R32F_0_SIZE)
#define _R32F_0_UV_TO_UV(uv) _textile_uvToUV(uv, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_0_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_0_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _R32F_0_OFFSET_F, _R32F_0_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_1_OFFSET (uval_mainImageSizeI * ivec2(0, 1))
#define _R32F_1_OFFSET_F (uval_mainImageSize * vec2(0, 1))
#define _R32F_1_SIZE uval_mainImageSizeI
#define _R32F_1_SIZE_F uval_mainImageSize
#define _R32F_1_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _R32F_1_OFFSET, _R32F_1_SIZE)
#define _R32F_1_UV_TO_UV(uv) _textile_uvToUV(uv, _R32F_1_OFFSET_F, _R32F_1_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_1_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _R32F_1_OFFSET_F, _R32F_1_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_1_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _R32F_1_OFFSET_F, _R32F_1_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_2_OFFSET (uval_mainImageSizeI * ivec2(1, 0))
#define _R32F_2_OFFSET_F (uval_mainImageSize * vec2(1, 0))
#define _R32F_2_SIZE uval_mainImageSizeI
#define _R32F_2_SIZE_F uval_mainImageSize
#define _R32F_2_TEXEL_TO_TEXEL(texelPos) _textile_texelToTexel(texelPos, _R32F_2_OFFSET, _R32F_2_SIZE)
#define _R32F_2_UV_TO_UV(uv) _textile_uvToUV(uv, _R32F_2_OFFSET_F, _R32F_2_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_2_UV_TO_GATHER_UV(uv) _textile_uvToGatherUV(uv, _R32F_2_OFFSET_F, _R32F_2_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define _R32F_2_TEXEL_TO_GATHER_UV(texelPos) _textile_texelToGatherUV(texelPos, _R32F_2_OFFSET_F, _R32F_2_SIZE_F, _R32F_ATLAS_SIZE_RCP)
#define history_viewZ_sample(x) texture(usam_r32f, _R32F_0_UV_TO_UV(x))
#define history_viewZ_gather(x, c) textureGather(usam_r32f, _R32F_0_UV_TO_GATHER_UV(x), c)
#define history_viewZ_gatherTexel(x, c) textureGather(usam_r32f, _R32F_0_TEXEL_TO_GATHER_UV(x), c)
#define history_viewZ_fetch(x) texelFetch(usam_r32f, _R32F_0_TEXEL_TO_TEXEL(x), 0)
#define history_viewZ_load(x) imageLoad(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x))
#define history_viewZ_store(x, v) imageStore(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicAdd(x, v) imageAtomicAdd(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicMin(x, v) imageAtomicMin(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicMax(x, v) imageAtomicMax(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicAnd(x, v) imageAtomicAnd(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicOr(x, v) imageAtomicOr(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicXor(x, v) imageAtomicXor(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicExchange(x, v) imageAtomicExchange(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v)
#define history_viewZ_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_r32f, _R32F_0_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_screenPixelSize_sample(x) texture(usam_r32f, _R32F_1_UV_TO_UV(x))
#define transient_screenPixelSize_gather(x, c) textureGather(usam_r32f, _R32F_1_UV_TO_GATHER_UV(x), c)
#define transient_screenPixelSize_gatherTexel(x, c) textureGather(usam_r32f, _R32F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_screenPixelSize_fetch(x) texelFetch(usam_r32f, _R32F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_screenPixelSize_load(x) imageLoad(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x))
#define transient_screenPixelSize_store(x, v) imageStore(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicAdd(x, v) imageAtomicAdd(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicMin(x, v) imageAtomicMin(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicMax(x, v) imageAtomicMax(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicAnd(x, v) imageAtomicAnd(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicOr(x, v) imageAtomicOr(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicXor(x, v) imageAtomicXor(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicExchange(x, v) imageAtomicExchange(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_screenPixelSize_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_caustics_input_sample(x) texture(usam_r32f, _R32F_2_UV_TO_UV(x))
#define transient_caustics_input_gather(x, c) textureGather(usam_r32f, _R32F_2_UV_TO_GATHER_UV(x), c)
#define transient_caustics_input_gatherTexel(x, c) textureGather(usam_r32f, _R32F_2_TEXEL_TO_GATHER_UV(x), c)
#define transient_caustics_input_fetch(x) texelFetch(usam_r32f, _R32F_2_TEXEL_TO_TEXEL(x), 0)
#define transient_caustics_input_load(x) imageLoad(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x))
#define transient_caustics_input_store(x, v) imageStore(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicAdd(x, v) imageAtomicAdd(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicMin(x, v) imageAtomicMin(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicMax(x, v) imageAtomicMax(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicAnd(x, v) imageAtomicAnd(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicOr(x, v) imageAtomicOr(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicXor(x, v) imageAtomicXor(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicExchange(x, v) imageAtomicExchange(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_input_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_caustics_remapped_sample(x) texture(usam_r32f, _R32F_1_UV_TO_UV(x))
#define transient_caustics_remapped_gather(x, c) textureGather(usam_r32f, _R32F_1_UV_TO_GATHER_UV(x), c)
#define transient_caustics_remapped_gatherTexel(x, c) textureGather(usam_r32f, _R32F_1_TEXEL_TO_GATHER_UV(x), c)
#define transient_caustics_remapped_fetch(x) texelFetch(usam_r32f, _R32F_1_TEXEL_TO_TEXEL(x), 0)
#define transient_caustics_remapped_load(x) imageLoad(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x))
#define transient_caustics_remapped_store(x, v) imageStore(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicAdd(x, v) imageAtomicAdd(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicMin(x, v) imageAtomicMin(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicMax(x, v) imageAtomicMax(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicAnd(x, v) imageAtomicAnd(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicOr(x, v) imageAtomicOr(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicXor(x, v) imageAtomicXor(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicExchange(x, v) imageAtomicExchange(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_remapped_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_r32f, _R32F_1_TEXEL_TO_TEXEL(x), v1, v2)
#define transient_caustics_final_sample(x) texture(usam_r32f, _R32F_2_UV_TO_UV(x))
#define transient_caustics_final_gather(x, c) textureGather(usam_r32f, _R32F_2_UV_TO_GATHER_UV(x), c)
#define transient_caustics_final_gatherTexel(x, c) textureGather(usam_r32f, _R32F_2_TEXEL_TO_GATHER_UV(x), c)
#define transient_caustics_final_fetch(x) texelFetch(usam_r32f, _R32F_2_TEXEL_TO_TEXEL(x), 0)
#define transient_caustics_final_load(x) imageLoad(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x))
#define transient_caustics_final_store(x, v) imageStore(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicAdd(x, v) imageAtomicAdd(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicMin(x, v) imageAtomicMin(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicMax(x, v) imageAtomicMax(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicAnd(x, v) imageAtomicAnd(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicOr(x, v) imageAtomicOr(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicXor(x, v) imageAtomicXor(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicExchange(x, v) imageAtomicExchange(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v)
#define transient_caustics_final_atomicCompSwap(x, v1, v2) imageAtomicCompSwap(uimg_r32f, _R32F_2_TEXEL_TO_TEXEL(x), v1, v2)
