#ifndef INCLUDE_util_CelestialObjects.glsl
#define INCLUDE_util_CelestialObjects.glsl

#include "BlackBody.glsl"

#ifdef SETTING_REAL_SUN_TEMPERATURE
#define SUN_TEMPERATURE 5772.0
#else
#define SUN_TEMPERATURE SETTING_SUN_TEMPERATURE
#endif

#define SUN_RADIUS (695700.0 * SETTING_SUN_RADIUS) // in km
#define SUN_DISTANCE (149597870.7 * SETTING_SUN_DISTANCE) // in km
#define SUN_ANGULAR_RADIUS atan(SUN_RADIUS / SUN_DISTANCE)
#define SUN_SOLID_ANGLE (2.0 * PI * (1.0 - sqrt(pow2(SUN_DISTANCE) - pow2(SUN_RADIUS)) / SUN_DISTANCE))

#define SUN_LUMINANCE blackBody_evalRadiance(SUN_TEMPERATURE)
#define SUN_ILLUMINANCE (SUN_LUMINANCE * SUN_SOLID_ANGLE)

#define MOON_RADIUS 1737.4
#define MOON_DISTANCE 384399
#define MOON_ANGULAR_RADIUS atan(MOON_RADIUS / MOON_DISTANCE)
#define MOON_SOLID_ANGLE (2.0 * PI * (1.0 - sqrt(pow2(MOON_DISTANCE) - pow2(MOON_RADIUS)) / MOON_DISTANCE))

#define MOON_ALBEDO (0.12 * vec3(0.8, 0.9, 1.0))
#define MOON_LUMINANCE (SUN_ILLUMINANCE * MOON_ALBEDO * RCP_PI)
#define MOON_ILLUMINANCE (MOON_LUMINANCE * MOON_SOLID_ANGLE)

#endif