#include "../_Util.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

void main() {
    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);
    uint bitFlag = uint(all(greaterThanEqual(coord, CLEAR_IMAGE_BOUND.xy)));
    bitFlag |= uint(all(lessThanEqual(coord, CLEAR_IMAGE_BOUND.zw)));
    if (bool(bitFlag)) {
        imageStore(CLEAR_IMAGE1, coord, CLEAR_COLOR1);
        imageStore(CLEAR_IMAGE2, coord, CLEAR_COLOR2);
    }
}
