#version 460 compatibility

#define GBUFFER_PASS_ALPHA_TEST a
#define GBUFFER_PASS_MATERIAL_ID_OVERRIDE MATERIAL_ID_HAND
#define GBUFFER_PASS_TEXTURED a
#define GBUFFER_PASS_VIEWZ_OVERRIDE -0.0001
#include "gbuffer/GBufferPass.frag"