import kotlin.io.path.Path
import kotlin.io.path.writeText

enum class ProgramType {
    BEGIN, SHADOWCOMP, PREPARE, DEFERRED, COMPOSITE;

    override fun toString(): String {
        return name.lowercase()
    }
}

val shadersPath = Path("../shaders")

@DslMarker
annotation class ProgramDsl

@ProgramDsl
class ProgramScope internal constructor() {
    private val toggleCond = mutableMapOf<String, MutableList<String>>()

    operator fun ProgramType.invoke(block: PassCollectionScope.() -> Unit) {
        PassCollectionScope(this).block()
    }

    @ProgramDsl
    inner class PassCollectionScope(val pass: ProgramType) {
        private var index = 1

        fun pass(vararg shaderPaths: String) {
            val prefix = "$pass${index++}"
            shaderPaths.forEachIndexed { index, string ->
                val suffix = if (index == 0) "" else "_${'a' + index - 1}"
                PassScope("$prefix$suffix", string).build()
            }
        }

        fun pass(shaderPath: String, block: PassScope.() -> Unit) {
            PassScope("$pass${index++}", shaderPath).apply(block).build()
        }

        @ProgramDsl
        inner class PassScope(private val passName: String, private val shaderPath: String) {
            private var cond: String? = null
            private val defines = mutableListOf<String>()
            private val constDefines = mutableListOf<String>()

            fun cond(condition: String) {
                cond = condition
            }

            fun define(name: String, value: Any? = null) {
                defines.add(if (value != null) "#define $name $value" else "#define a")
            }

            fun constDefine(name: String, value: Any? = null) {
                constDefines.add(if (value != null) "#define $name $value" else "#define a")
            }

            internal fun build() {
                cond?.takeIf { it.isNotBlank() }?.let {
                    this@ProgramScope.toggleCond.computeIfAbsent(it) { mutableListOf() }.add(passName)
                }

                val outputPath = shadersPath.resolve("$passName.csh")
                val text = buildString {
                    appendLine(
                        """
                        #version 460 compatibility
                        #define COMP 1
                        """.trimIndent()
                    )
                    if (defines.isNotEmpty()) {
                        defines.forEach(::appendLine)
                    }
                    if (constDefines.isNotEmpty()) {
                        appendLine("/*const*/")
                        constDefines.forEach(::appendLine)
                        appendLine("/*const*/")
                    }
                    appendLine()
                    appendLine("#include \"$shaderPath\"")
                }
                outputPath.writeText(text)
            }
        }
    }

    fun build() {
        Path("programs.shaders.properties").writeText(buildString {
            appendLine("# This file is generated by programs.main.kts. Do not edit this file manually.")
            appendLine("# ------------------------------------------------------ Enabling ------------------------------------------------------")
            toggleCond.entries.asSequence()
                .filter { it.value.isNotEmpty() }
                .forEach {
                    appendLine("#if ${it.key}")
                    it.value.forEach { passName ->
                        appendLine("program.$passName.enabled=true")
                    }
                    appendLine("#else")
                    it.value.forEach { passName ->
                        appendLine("program.$passName.enabled=false")
                    }
                    appendLine("#endif")
                }
        })
    }
}

fun programs(block: ProgramScope.() -> Unit) {
    ProgramScope().apply(block).build()
}

programs {
    ProgramType.BEGIN {
        pass(
            "/pass/begin/UpdateGlobalData.comp.glsl",
            "/pass/begin/ClearRTWSM.comp.glsl",
            "/techniques/atmospherics/air/lut/GenerateTransmittance.comp.glsl"
        )
        pass(
            "/techniques/atmospherics/air/SliceEndPoints.comp.glsl",
            "/techniques/atmospherics/air/lut/GenerateMultiSctr.comp.glsl",
            "/pass/begin/ClearScreen1.comp.glsl",
            "/pass/begin/ClearScreen2.comp.glsl"
        )
        pass(
            "/techniques/atmospherics/clouds/amblut/Sample.comp.glsl",
            "/techniques/atmospherics/air/lut/GenerateSkyViewLUT.comp.glsl"
        )
        pass(
            "/techniques/atmospherics/clouds/amblut/Gather.comp.glsl",
            "/pass/begin/ClearEnvProbe.comp.glsl"
        )
        pass("/pass/begin/InitThreadGroupTilling.glsl")
        pass("/pass/begin/ClearScreen3.comp.glsl") {
            cond("defined(VOXY)")
        }
    }
}