import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import kotlin.math.abs
import kotlin.math.sqrt

data class V3(val x: Double, val y: Double, val z: Double) {
    operator fun minus(v: V3) = V3(x - v.x, y - v.y, z - v.z)
    fun cross(v: V3) = V3(y * v.z - z * v.y, z * v.x - x * v.z, x * v.y - y * v.x)
}
fun rayBox(o: V3, d: V3, lo: V3, hi: V3): Pair<Double, V3>? {
    val os = doubleArrayOf(o.x, o.y, o.z)
    val ds = doubleArrayOf(d.x, d.y, d.z)
    val ls = doubleArrayOf(lo.x, lo.y, lo.z)
    val hs = doubleArrayOf(hi.x, hi.y, hi.z)
    var enter = Double.NEGATIVE_INFINITY
    var exit = Double.POSITIVE_INFINITY
    var normal = V3(0.0, 0.0, 0.0)
    for (axis in 0..2) {
        if (abs(ds[axis]) < 1e-12) {
            if (os[axis] !in ls[axis]..hs[axis]) return null
            continue
        }
        val a = (ls[axis] - os[axis]) / ds[axis]
        val b = (hs[axis] - os[axis]) / ds[axis]
        val near = minOf(a, b)
        if (near > enter) {
            enter = near
            val s = if (ds[axis] > 0) -1.0 else 1.0
            normal = when (axis) { 0 -> V3(s,0.0,0.0); 1 -> V3(0.0,s,0.0); else -> V3(0.0,0.0,s) }
        }
        exit = minOf(exit, maxOf(a, b))
    }
    return if (enter <= exit && exit >= 0) maxOf(enter, 0.0) to normal else null
}
val root = Path.of("..").toAbsolutePath().normalize()
fun read(path: String) = Files.readString(root.resolve(path))
val failures = mutableListOf<String>()
fun expect(text: String, token: String, label: String) { if (!text.contains(token)) failures += label + ": missing " + token }

val mappings = read("shaders/block.properties")
val models = read("shaders/techniques/voxel/BlockModels.glsl")
val hardcoded = read("shaders/util/HardcodedPBR.glsl")
val shadow = read("shaders/pass/geometry/ShadowPass.vert.glsl")
val trace = read("shaders/techniques/voxel/VoxelTrace.glsl")
val surface = read("shaders/techniques/voxel/SurfaceData.glsl")
val texcoords = read("shaders/techniques/voxel/VoxelFaceTexcoords.glsl")
val clear = read("shaders/pass/setup/ClearVoxelFaceTexcoords.comp.glsl")
val properties = read("scripts/shaders.properties")

val states = listOf(
    "oak_slab:type=bottom", "oak_slab:type=top",
    "oak_stairs:facing=east:half=bottom:shape=inner_left",
    "oak_door:facing=east:half=lower:hinge=left:open=true",
    "oak_fence:east=false:north=false:south=false:west=false"
)
fun id(state: String) = Regex("(?m)^block\\.(\\d+) = " + Regex.escape(state) + "$")
    .find(mappings)?.groupValues?.get(1)?.toInt()
val ids = states.map { state -> id(state) ?: run { failures += "mapping missing: " + state; -1 } }
val allIds = Regex("(?m)^block\\.(\\d+) =").findAll(mappings).map { it.groupValues[1].toInt() }.toList()
val maxId = allIds.maxOrNull()!!
if (maxId >= 16384) failures += "material ID >= 16384"
val lutBytes = Files.readAllBytes(root.resolve("shaders/textures/pbr_lut_0.bin"))
if (lutBytes.size % 4 != 0) failures += "PBR LUT byte size not divisible by 4"
val lutWidth = lutBytes.size / 4L
if (lutWidth != maxId + 1L) failures += "PBR LUT width $lutWidth != max material ID + 1 (${maxId + 1})"
ids.filter { it >= 0 }.forEach { expect(models, "case " + it + "u:", "model case") }
val modeledId = ids.firstOrNull { it >= 0 && models.contains("case " + it + "u:") }
if (modeledId == null) {
    failures += "no modeled LUT word selected via block.properties"
} else {
    val raw = ByteBuffer.wrap(lutBytes).order(ByteOrder.LITTLE_ENDIAN).getInt(modeledId * 4).toLong() and 0xFFFF_FFFFL
    val toggled = raw xor (1L shl 30)
    if ((raw and (1L shl 30)) == 0L) failures += "modeled LUT word does not set bit 30"
    if (((raw shr 16) and 255L) != ((toggled shr 16) and 255L)) failures += "bit 30 changes roughness byte at offset 16"
    if (((raw shr 24) and 255L) == ((toggled shr 24) and 255L)) failures += "modeled LUT word does not expose old offset-24 overlap"
}
expect(models, "Generated by Shadesmith from Minecraft 26.2", "provenance")
expect(models, "bool voxel_intersectBlockModel(", "model API")
if (Regex("(?m)\\b(?:const\\s+)?(?:vec[234]|u?int|float|bool)\\s+\\w+\\s*\\[").containsMatchIn(models)) failures += "generated local/const array"

expect(hardcoded, "bool hasBlockModel;", "PBR member")
expect(hardcoded, "pbr.hasBlockModel = bitfieldExtract(rawData.x, 30, 1) == 1u;", "PBR bit 30")
expect(hardcoded, "pbr.roughness = unpackU8(bitfieldExtract(rawData.x, 16, 8));", "PBR roughness bit 16")
if (hardcoded.contains("pbr.roughness = unpackU8(bitfieldExtract(rawData.x, 24, 8));")) failures += "PBR roughness still decodes obsolete bit 24"
expect(shadow, "hardcoded.isFullCube || hardcoded.hasBlockModel", "voxelization gate")
if (shadow.contains("hardcoded.emissive > 0.0")) failures += "obsolete emissive voxelization"
expect(shadow, "materialID != MATERIAL_ID_WATER", "water exclusion")
expect(trace, "#include \"/util/HardcodedPBR.glsl\"", "trace PBR include")
expect(trace, "#include \"/techniques/voxel/BlockModels.glsl\"", "trace model include")
expect(trace, "voxel_intersectBlockModel(", "trace model call")
expect(trace, "hardcoded.isFullCube", "full-cube fast path")
expect(trace, "hardcoded.hasBlockModel", "unsupported exclusion")
listOf("ray.lastT = lastT;", "ray.level = level;", "ray.fullMorton = fullMorton;").forEach { expect(trace, it, "resumable state") }
val emptyStep = trace.indexOf("// ---- Empty child")
val blockPosUpdate = trace.indexOf("blockPos = exitBlockPos;", emptyStep)
val finalAxisUpdate = trace.indexOf("blockPos.x = clamp", blockPosUpdate)
val updatedBounds = trace.indexOf("if (uint(blockPos.x | blockPos.y | blockPos.z) >= uint(GRID_BLOCKS))", finalAxisUpdate)
val updatedPack = trace.indexOf("fullMorton = _voxel_packBlockPos(blockPos);", blockPosUpdate)
if (emptyStep < 0 || blockPosUpdate < 0 || finalAxisUpdate < 0 || updatedBounds < 0 || updatedPack < 0 ||
    !(blockPosUpdate < finalAxisUpdate && finalAxisUpdate < updatedBounds && updatedBounds < updatedPack)) {
    failures += "updated blockPos bounds check must precede pack after all axis updates"
}
val fullCubeStart = trace.indexOf("if (hardcoded.isFullCube)")
val modelStart = trace.indexOf("if (hardcoded.hasBlockModel", fullCubeStart)
if (fullCubeStart < 0 || modelStart < 0 || !trace.substring(fullCubeStart, modelStart).contains("ray.level = 0;")) {
    failures += "full-cube hit does not clear ray.level"
}
val modelHitStart = trace.indexOf("if (voxel_intersectBlockModel(", modelStart)
val modelMissStart = trace.indexOf("isHit = false;", modelHitStart)
if (modelHitStart < 0 || modelMissStart < 0 || !trace.substring(modelHitStart, modelMissStart).contains("ray.level = 0;")) {
    failures += "block-model hit does not clear ray.level"
}
val writebackStart = trace.indexOf("// Write back state")
val resultStart = trace.indexOf("VoxelHit result;", writebackStart)
if (writebackStart < 0 || resultStart < 0) {
    failures += "trace writeback section missing"
} else {
    val writeback = trace.substring(writebackStart, resultStart)
    val levelWrite = writeback.indexOf("ray.level = level;")
    val activeGuard = writeback.indexOf("if (level != 0)")
    val mortonWrite = writeback.indexOf("ray.fullMorton = fullMorton;")
    if (levelWrite < 0 || activeGuard < levelWrite || mortonWrite < activeGuard) failures += "terminal writeback must propagate level and guard fullMorton"
}
expect(surface, "gData.geomNormal = hit.normal;", "exact normal")
expect(texcoords, "#define VOXEL_FACE_TEXCOORD_MATERIALS 16384", "texcoord capacity")
expect(clear, "const ivec3 workGroups = ivec3(768, 1, 1);", "clear size")
expect(properties, "customTexture.usam_pbrLUT0=textures/pbr_lut_0.bin TEXTURE_1D R32UI $lutWidth ", "LUT width")
expect(properties, "bufferObject.9=1572864", "SSBO size")

val down = rayBox(V3(.25,1.0,.25), V3(0.0,-1.0,0.0), V3(0.0,0.0,0.0), V3(1.0,.5,1.0))
val up = rayBox(V3(.25,0.0,.25), V3(0.0,1.0,0.0), V3(0.0,.5,0.0), V3(1.0,1.0,1.0))
if (down != (0.5 to V3(0.0,1.0,0.0))) failures += "bottom slab numeric hit"
if (up != (0.5 to V3(0.0,-1.0,0.0))) failures += "top slab numeric hit"
val n = (V3(1.0,0.0,1.0) - V3(0.0,0.0,0.0)).cross(V3(0.0,1.0,0.0) - V3(0.0,0.0,0.0))
val len = sqrt(n.x*n.x + n.y*n.y + n.z*n.z)
if (abs(abs(n.x/len) - sqrt(.5)) > 1e-9 || abs(abs(n.z/len) - sqrt(.5)) > 1e-9) failures += "rotated normal"
val first = rayBox(V3(-1.0,.75,.5), V3(1.0,0.0,0.0), V3(0.0,0.0,0.0), V3(1.0,.5,1.0))
val later = rayBox(V3(-1.0,.75,.5), V3(1.0,0.0,0.0), V3(2.0,0.0,0.0), V3(3.0,1.0,1.0))
if (first != null || later?.first != 3.0) failures += "model-miss continuation"
if (rayBox(V3(-1.0,.25,.25), V3(1.0,0.0,0.0), V3(0.0,0.0,0.0), V3(1.0,1.0,1.0))?.first != 1.0) failures += "full-cube entry"
fun voxelized(id: Int, full: Boolean, model: Boolean) = id != 0 && id != 1 && (full || model)
if (voxelized(1,false,true) || voxelized(0,true,false) || voxelized(2,false,false)) failures += "water/zero/unsupported exclusion"
data class DdaStep(val level: Int, val packedBlockPos: Int?)
fun packBlockPos(blockPos: Int, gridBlocks: Int): Int {
    check(blockPos in 0 until gridBlocks)
    return blockPos
}
fun stepEmptyCell(blockPos: Int, stepDir: Int, gridBlocks: Int): DdaStep {
    val updatedBlockPos = blockPos + stepDir
    if (updatedBlockPos !in 0 until gridBlocks) return DdaStep(0, null)
    return DdaStep(1, packBlockPos(updatedBlockPos, gridBlocks))
}
val GRID_BLOCKS = 64
val positiveEdge = stepEmptyCell(GRID_BLOCKS - 1, 1, GRID_BLOCKS)
val negativeEdge = stepEmptyCell(0, -1, GRID_BLOCKS)
val interior = stepEmptyCell(17, 1, GRID_BLOCKS)
if (positiveEdge.level != 0 || positiveEdge.packedBlockPos != null) failures += "positive edge must terminate without packing"
if (negativeEdge.level != 0 || negativeEdge.packedBlockPos != null) failures += "negative edge must terminate without packing"
if (interior.level == 0 || interior.packedBlockPos != 18) failures += "interior step must remain active and pack"

check(failures.isEmpty()) { "Voxel trace contract failed:\n" + failures.joinToString("\n") { "- " + it } }
println("Voxel trace contract PASS: " + allIds.size + " mappings, max ID " + maxId + ", Minecraft 26.2")
